project:
  type: website
  output-dir: docs
  pre-render: scripts/generate_publications.py

profile:
  default: html

website:
  title: "Simen Kvaal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: github.qmd
        text: GitHub
      - href: cv.qmd
        text: CV

